export const endpoints = {
  SEND_LOGIN_OTP: `/login`,
  VERIFY_LOGIN_OTP: `/login/verify`,
  LOGOUT: "/api/auth/logout",
  SEND_REGISTER_OTP: `/register`,
  VERIFY_REGISTER_OTP: `/register/verify`,
  RESEND_OTP: `/resendOtp`,
  USER_INFO: "/userprofile/information",
  REFRESH_TOKEN: `/refreshAccessToken`,
  GET_STORE: "store/collection/store/:storeID",
  SEARCH_PRODUCTS: "/store/inside/search",
  ADD_ADDRESS: "/add-address",
  DELETE_ADDRESS: "/addresses/:addressID/delete-address",
  EDIT_ADDRESS: "/:addressID/edit-address",
  ADDRESSLIST: "/addresses",
  MY_ORDERS: "/orders/my-orders",
  ORDER_DETAILS: "/orders/my-orders/orderdetail",
  PLACE_ORDER: "/orders/checkout",
};
